3. How does the portrayal of historical events in movies vary based on the country of production?
This question could analyze narrative and thematic differences in films about the same historical events, revealing how cultural perspectives and national histories influence storytelling and representation in movies from different countries.

In [ ]:

import pandas as pd
import numpy as np
import csv
import re
import nltk
from nltk.sentiment import SentimentIntensityAnalyzer
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [2]:
# Download necessary NLTK resources
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('vader_lexicon')  # Required for SentimentIntensityAnalyzer

# Set of English stopwords
stop_words = set(stopwords.words("english"))

[nltk_data] Error loading stopwords: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>
[nltk_data] Error loading punkt: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>
[nltk_data] Error loading vader_lexicon: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>

Adding the plot summaries

In [3]:
input_file = 'data/plot_summaries.txt'
output_file = 'data/plot_summaries.csv'

#with open(input_file, 'r', encoding='utf-8') as infile, open(output_file, 'w', encoding='utf-8', newline='') as outfile:
   # writer = csv.writer(outfile)
   # writer.writerow(['Movie_ID', 'summary'])  # Write the header row

    
   # for line in infile:
        
        #parts = line.strip().split('\t', 1)  # Splitting on the first tab to separate ID and summary
        #if len(parts) == 2:  # Check if line has both ID and summary
           # movie_id, summary = parts
           # writer.writerow([movie_id, summary])

In [4]:
filtered_movies_df = pd.read_csv('data/filtered_movie_data.csv')
plot_summaries_df = pd.read_csv('data/plot_summaries.csv')

In [5]:
dataset_with_summaries = pd.merge(filtered_movies_df, plot_summaries_df, on='Movie_ID')

In [6]:
dataset_with_summaries.to_csv('data/movies_with_summaries.csv', index=False)

Cleaning: removing punctuation and converting to lowercase

In [7]:
df = pd.read_csv('data/movies_with_summaries.csv')
df.head()

,Movie_ID,IMDb_Index,Title,Original_Title,Release_Date,Year,Genres,Genres_IMDb,Rating,Votes,Revenue,Length,Languages,Countries,summary
0,975900,tt0228333,Ghosts of Mars,Ghosts of Mars,2001-08-24,2001,"['Thriller', 'Science Fiction', 'Horror', 'Adv...","['Action,Horror,Sci-Fi']",4.9,58872,14010832.0,98.0,['English Language'],['United States of America'],"Set in the second half of the 22nd century, th..."
1,261236,tt0083949,A Woman in Flames,Die flambierte Frau,1983,1983,['Drama'],['Drama'],5.9,648,NaN,106.0,['German Language'],['Germany'],"Eva, an upper class housewife, becomes frustra..."
2,171005,tt0097499,Henry V,Henry V,1989-11-08,1989,"['Costume drama', 'War film', 'Epic', 'Period ...","['Biography,Drama,History']",7.5,32088,10161099.0,137.0,['English Language'],['United Kingdom'],{{Plot|dateAct 1Act 2Act 3Act 4Act 5 Finally n...
3,77856,tt0058331,Mary Poppins,Mary Poppins,1964-08-27,1964,"['ChildrensFamily', 'Musical', 'Fantasy', 'Com...","['Comedy,Family,Fantasy']",7.8,189202,102272727.0,139.0,['English Language'],['United States of America'],The film opens with Mary Poppins perched in a...
4,32456683,tt0061637,Die Fahne von Kriwoj Rog,Die Fahne von Kriwoj Rog,1967,1967,[],['Drama'],7.7,24,NaN,108.0,['German Language'],['German Democratic Republic'],"Otto Brosowski, a communist miner, writes to t..."

In [8]:
# Function to clean text data
def clean_text(text):
    # Remove special characters and digits
    cleaned_text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    # Convert text to lowercase
    text = cleaned_text.lower()
    return text

In [9]:
df['cleaned_summary'] = df['summary'].apply(clean_text)

In [10]:
df.head()

,Movie_ID,IMDb_Index,Title,Original_Title,Release_Date,Year,Genres,Genres_IMDb,Rating,Votes,Revenue,Length,Languages,Countries,summary,cleaned_summary
0,975900,tt0228333,Ghosts of Mars,Ghosts of Mars,2001-08-24,2001,"['Thriller', 'Science Fiction', 'Horror', 'Adv...","['Action,Horror,Sci-Fi']",4.9,58872,14010832.0,98.0,['English Language'],['United States of America'],"Set in the second half of the 22nd century, th...",set in the second half of the 22nd century the...
1,261236,tt0083949,A Woman in Flames,Die flambierte Frau,1983,1983,['Drama'],['Drama'],5.9,648,NaN,106.0,['German Language'],['Germany'],"Eva, an upper class housewife, becomes frustra...",eva an upper class housewife becomes frustrate...
2,171005,tt0097499,Henry V,Henry V,1989-11-08,1989,"['Costume drama', 'War film', 'Epic', 'Period ...","['Biography,Drama,History']",7.5,32088,10161099.0,137.0,['English Language'],['United Kingdom'],{{Plot|dateAct 1Act 2Act 3Act 4Act 5 Finally n...,plotdateact 1act 2act 3act 4act 5 finally nego...
3,77856,tt0058331,Mary Poppins,Mary Poppins,1964-08-27,1964,"['ChildrensFamily', 'Musical', 'Fantasy', 'Com...","['Comedy,Family,Fantasy']",7.8,189202,102272727.0,139.0,['English Language'],['United States of America'],The film opens with Mary Poppins perched in a...,the film opens with mary poppins perched in a...
4,32456683,tt0061637,Die Fahne von Kriwoj Rog,Die Fahne von Kriwoj Rog,1967,1967,[],['Drama'],7.7,24,NaN,108.0,['German Language'],['German Democratic Republic'],"Otto Brosowski, a communist miner, writes to t...",otto brosowski a communist miner writes to the...

In [11]:
df.shape

(29177, 16)

In [12]:
minidf=df.head(1000)

In [13]:
synopses=minidf["cleaned_summary"].tolist()

##df['tokenized_summaries'] = df['cleaned_summary'].apply(word_tokenize)

In [14]:
# Process the documents: tokenize and remove stopwords
processed_docs = []
for synopsis in synopses:
    tokens = word_tokenize(synopsis.lower())
    # Keep alphanumeric tokens that are not stopwords
    filtered_tokens = [word for word in tokens if word.isalnum() and word not in stop_words]
    processed_docs.append(filtered_tokens)

In [15]:
# Initialize the Sentiment Analyzer
analyzer = SentimentIntensityAnalyzer()

# Perform Sentiment Analysis
sentiment_scores = []
for tokens in processed_docs:
    # Join tokens back into a string
    text = ' '.join(tokens)
    # Get sentiment scores for the text
    score = analyzer.polarity_scores(text)
    sentiment_scores.append(score)

In [16]:
# Convert the list of sentiment scores to a DataFrame
sentiment_df = pd.DataFrame(sentiment_scores)

# Reset the index of 'minidf' to align with 'sentiment_df'
minidf = minidf.reset_index(drop=True)

# Concatenate the sentiment scores with the original DataFrame
minidf = pd.concat([minidf, sentiment_df], axis=1)

# Display the relevant columns
print(minidf[['cleaned_summary', 'neg', 'neu', 'pos', 'compound']])

                                       cleaned_summary    neg    neu    pos  \
0    set in the second half of the 22nd century the...  0.228  0.659  0.113
1    eva an upper class housewife becomes frustrate...  0.159  0.625  0.216
2    plotdateact 1act 2act 3act 4act 5 finally nego...  0.055  0.835  0.110
3    the film opens with mary poppins  perched in a...  0.115  0.735  0.151
4    otto brosowski a communist miner writes to the...  0.148  0.685  0.166
..                                                 ...    ...    ...    ...
995  sam baldwin a chicago architect loses his wife...  0.103  0.770  0.127
996  a teenage outcast road movie jimmy and judy fo...  0.187  0.592  0.221
997  in 1820 boston dancing teacher jonathan pride ...  0.126  0.758  0.116
998  it follows the young romeo and his best friend...  0.161  0.598  0.241
999  sam houston a lawyer and former governor of te...  0.089  0.742  0.169

     compound
0     -0.9889
1      0.9543
2      0.3182
3      0.9891
4      0.3612
..        ...
995    0.6908
996    0.5719
997   -0.5574
998    0.8402
999    0.8860

[1000 rows x 5 columns]